### ISSUE TITLE
Update to FreeRTOS 8.2

### ISSUE THREAD

**Issue by GunterO** [greiman/FreeRTOS-Arduino#1]
Hello,

Thanks for your work on this port! 
I wonder, do you have any plans to update it to FreeRTOS 8.2 (Task Notifications)?

Regards,
Gunter

**Comment by greiman** [comment]
Gunter,

I will likely update the FreeRTOS port next time I update ChibiOS.  

I don’t use FreeRTOS any more since ChibiOS is much better for my projects.

Bill

From: GunterO 
Sent: Thursday, January 29, 2015 4:46 AM
To: greiman/FreeRTOS-Arduino 
Subject: [FreeRTOS-Arduino] Update to FreeRTOS 8.2 (#1)

Hello,

Thanks for your work on this port! 
I wonder, do you have any plans to update it to FreeRTOS 8.2 (Task Notifications)?

Regards,
Gunter

**Comment by GunterO** [comment]
Ok, thanks! 
Maybe I should switch to ChibiOS as well, looks very nice. Thanks for the tip :-)

**Comment by greiman** [comment]
I will soon post a FreeRTOS 8.2 port.  I just need to do some more tests.

**Comment by GunterO** [comment]
Thanks, I really appreciate this!

**Comment by hemanzur** [comment]
Hi, thank you so much for this port to the arduino.
I've playing with the examples and reading the book and it works really well.

The thing is that I've been having difficulties with timers:

I have this sketch:
```c++
#include <FreeRTOS_AVR.h>
#include <basic_io_avr.h>
#include "utility/timers.h"

TimerHandle_t timer1;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  int x=1;
  //xTimerCreate();
  timer1 = xTimerCreate("timer1", 500, pdFALSE, (void*)x, timer1_callback);
  Serial.print("Before execution: ");
  Serial.println(millis());
  
  xTimerStart(timer1, 0);
  vTaskStartScheduler();
  for( ;; );
}


void loop() {
  // put your main code here, to run repeatedly:

}


void timer1_callback( TimerHandle_t pxTimer){
  Serial.println("Ready !");
}
```


But it doesn't compile:

```
timer_test.cpp.o: In function `setup':
/opt/arduino/timer_test.ino:12: undefined reference to `xTimerCreate'
/opt/arduino/timer_test.ino:16: undefined reference to `xTimerGenericCommand'
collect2: error: ld returned 1 exit status
Error compiling.
```

I have tried many tricks reated to making the compiler recgnize the mentioned functions but none of those work.

Any ideas ?
Thanks
