### ISSUE TITLE
Memory 

### ISSUE THREAD

**Issue by Formator** [greiman/FreeRTOS-Arduino#11]
Hi

In my repository I have added https://github.com/Formator/FreeRTOS-Arduino/blob/master/libraries/FreeRTOS_ARM/examples/frMemTest/frMemTest.ino which is demo for Memory issue. Problem is that heap and stack memory overlap each other. 

My demo output on Arduino DUE:
```
    arena=0
  ordblks=0
 uordblks=0
 fordblks=0
 keepcost=0
RAM Start 20070000
Data/Bss end 2007144c
Heap End 2007144c
Stack Ptr 20087f98
RAM End 20088000
Heap RAM Used: 0
Program RAM Used 5196
Estimated Free RAM: 93004

    arena=7092
  ordblks=1
 uordblks=3572
 fordblks=3520
 keepcost=3520
RAM Start 20070000
Data/Bss end 2007144c
Heap End 20073000
Stack Ptr 20071a18
RAM End 20088000
Heap RAM Used: 3572
Program RAM Used 5196
Estimated Free RAM: -9128
```

First output is before FreeRTOS start, second output and all outputs after that are outputs from FreeRTOS task. I have tested this example also on ChRt (ChibiOS/RT) but I'm getting similar negative free ram numbers...

Maybe I'm doing something wrong or is here some OS Memory issue?

**Comment by greiman** [comment]
Dynamic memory does not work for with threads for most versions of Arduino.  There are multiple issues with malloc on Arduino

Various parts of the Arduino system uses malloc so you can't replace malloc with a thread safe versions of FreeRTOS's memory [allocation](http://www.freertos.org/a00111.html).

**Comment by Formator** [comment]
I understand your answer but real question here is do heap and stack mamory overlaps for real or do I have wrong codo to show free mem?

I have come to this because I'm using your FreeRTOS port in my other project and suddenly I had experienced  mcu freeze or variable redefine it self and other memory related symptoms.

**Comment by greiman** [comment]
When you execute this in a thread you will get an address in the heap.  FreeRTOS creates the thread's stack on the heap.

`register char * stack_ptr asm("sp");`

The next line can fail for the version of malloc on some ARM Arduino boards. It may be OK on Due.

`char *heapend = sbrk(0);`

If you create all threads in setup  and don't call malloc directly you should be OK.  FreeRTOS assumes you will use it's memory allocator.  Here is the code is in heap_3.c

This allocator may fail in threads if malloc fails in threads.  Some versions of malloc look at the stack pointer and find it in the heap and return null.

```
void *pvPortMalloc( size_t xWantedSize )
{
void *pvReturn;

	vTaskSuspendAll();
	{
		pvReturn = malloc( xWantedSize );
		traceMALLOC( pvReturn, xWantedSize );
	}
	( void ) xTaskResumeAll();

	#if( configUSE_MALLOC_FAILED_HOOK == 1 )
	{
		if( pvReturn == NULL )
		{
			extern void vApplicationMallocFailedHook( void );
			vApplicationMallocFailedHook();
		}
	}
	#endif

	return pvReturn;
}
/*-----------------------------------------------------------*/

void vPortFree( void *pv )
{
	if( pv )
	{
		vTaskSuspendAll();
		{
			free( pv );
			traceFREE( pv, 0 );
		}
		( void ) xTaskResumeAll();
	}
}
```

**Comment by Formator** [comment]
Thank you for your answer now I know that my method show wrong free mem. If someone will have the same issue I would also suggest [this video](https://youtu.be/bLQWB4H0TpE).

Is there any chance that API method xPortGetFreeHeapSize could work, because I have try it but then portUSING_MPU_WRAPPERS must be defined and when I do that, I get many errors.

**Comment by greiman** [comment]
Your use of mallinfo is about the best you can do.

xPortGetFreeHeapSize() will be not defined since I use heap_3.c.   heap_3.c shown above, uses malloc() so there is not a definite amount of free heap.  The stack and heap share the same area so the heap can grow.  Also the heap is fragmented so it contains free memory. 

heap_1.c, heap_2.c, and  heap_4.c use a single array of size TOTAL_HEAP_SIZE for the FreeRTOS heap. xPortGetFreeHeapSize () returns how much memory is free in this array.

heap_5.c allows several arrays to be used and xPortGetFreeHeapSize () returns the total free memory in these arrays.

See [this](http://www.freertos.org/a00111.html) for more detail.

**Comment by Formator** [comment]
Thank you for your answers I will also try heap 2 to get more control over heap.
