### ISSUE TITLE
Can the tick rate be adjusted?

### ISSUE THREAD

**Issue by Vlamonster** [greiman/FreeRTOS-Arduino#15]
I tried playing with this value, but it seems that if I set it to for instance 500, then it will actually *double* the speed.

`#define configTICK_RATE_HZ ( ( TickType_t ) (F_CPU/16384L))`

**Comment by greiman** [comment]
This library is unsupported since it is eight years old.  There are many recent ports to Arduino like [this](https://github.com/feilipu/Arduino_FreeRTOS_Library).
