### ISSUE TITLE
Free_RTOS_ARM compatibility with teensy 3.1

### ISSUE THREAD

**Issue by tungkaG** [greiman/FreeRTOS-Arduino#16]
Hello, i am using a teensy 3.1 board. PlatformIO is able to find my library however when running the example frBLink.ino i got an error:
in function `pendablesrvreq_isr':
EventResponder.cpp:(.text.pendablesrvreq_isr+0x0): multiple definition of `pendablesrvreq_isr'; .pio\build\main\lib632\libFreeRTOS_ARM_AMDC.a(port.c.o):port.c:(.text.pendablesrvreq_isr+0x0): first defined here
in function `systick_isr':
EventResponder.cpp:(.text.systick_isr+0x0): multiple definition of `systick_isr'; .pio\build\main\lib632\libFreeRTOS_ARM_AMDC.a(port.c.o):port.c:(.text.systick_isr+0x0): first defined here
Could this be an issue?

Also, is it possible to configure this library so that it is compatible with teensy 4.1? Thank you!

**Comment by greiman** [comment]
This library is no longer supported since Amazon acquired FreeRTOS.
