### ISSUE TITLE
Need to include <avr/sleep.h> to use your code

### ISSUE THREAD

**Issue by k-g** [greiman/FreeRTOS-Arduino#3]
Specifically, in arduino 1.6.7, I can't get your code to compile without the inclusion: http://feilipu.me/2015/11/24/arduino_freertos/

**Comment by greiman** [comment]
All of the FreeRTOS_AVR examples compile on 1.6.7 without

```
#include <avr/sleep.h>
```

You must use some power saving calls in your app that require avr/sleep.h

Also I think you are using the wrong library.  This, FreeRTOS_AVR, is not the library from this article

http://feilipu.me/2015/11/24/arduino_freertos/
