### ISSUE TITLE
Adding Arduino Zero/SamD21 processors

### ISSUE THREAD

**Issue by BriscoeTech** [greiman/FreeRTOS-Arduino#6]
Hello Greiman,

Thank you for porting freeRTOS to the Arduino, I have been using your libraries alot these past few months and am going to use them in many Arduino projects to come. I appreciate all the time and RTOS examples you included with the libraries, has made it quite easy and enjoyable to poke around and learn FreeRtos.

I would like to port your libraries over to the Arduino Zero/SamD21 line of processors as well. Both Sparkfun and Adafruit both have very popular SamD21 board lines right now and have plenty of ram to support a lot of task stacks. I just ram out of ram on a large AVR project and its time to move up a processor line.

I am messaging to get your advice or assistance on what would need to be done to port to this new processor. I have Avr Studio and freeRTOS examples running on the samD21, would be nice to focus my attention to the proper source files :-)

**Comment by greiman** [comment]
I had the Arduino group add some special hooks for the Due port.  

I don’t know what will be needed for SAMD21 so I can’t help you and I don’t plan on updating the FreeRTOS library.

You should just use a newer version of FreeRTOS without the Arduino stuff.  I suspect Atmel already has a port.

From: BriscoeTech 
Sent: Thursday, November 10, 2016 10:44 AM
To: greiman/FreeRTOS-Arduino 
Subject: [greiman/FreeRTOS-Arduino] Adding Arduino Zero/SamD21 processors (#6)

Hello Greiman,

Thank you for porting freeRTOS to the Arduino, I have been using your libraries alot these past few months and am going to use them in many Arduino projects to come. I appreciate all the time and RTOS examples you included with the libraries, has made it quite easy and enjoyable to poke around and learn FreeRtos.

I would like to port your libraries over to the Arduino Zero/SamD21 line of processors as well. Both Sparkfun and Adafruit both have very popular SamD21 board lines right now and have plenty of ram to support a lot of task stacks. I just ram out of ram on a large AVR project and its time to move up a processor line.

I am messaging to get your advice or assistance on what would need to be done to port to this new processor. I have Avr Studio and freeRTOS examples running on the samD21, would be nice to focus my attention to the proper source files :-)

Would love to hear back from you, and thanks again!
Hello Greiman,

Thank you for porting freeRTOS to the Arduino, I have been using your libraries alot these past few months and am going to use them in many Arduino projects to come. I appreciate all the time and RTOS examples you included with the libraries, has made it quite easy and enjoyable to poke around and learn FreeRtos.

I would like to port your libraries over to the Arduino Zero/SamD21 line of processors as well. Both Sparkfun and Adafruit both have very popular SamD21 board lines right now and have plenty of ram to support a lot of task stacks. I just ram out of ram on a large AVR project and its time to move up a processor line.

I am messaging to get your advice or assistance on what would need to be done to port to this new processor. I have Avr Studio and freeRTOS examples running on the samD21, would be nice to focus my attention to the proper source files :-)

Would love to hear back from you, and thanks again!

**Comment by greiman** [comment]
I had the Arduino group add some special hooks for the Due port. 

I don’t know what will be needed for SAMD21 so I can’t help you and I don’t plan on updating the FreeRTOS library. 

You should just use a newer version of FreeRTOS without the Arduino stuff. I suspect Atmel already has a port.
