### ISSUE TITLE
FreeRTOS_AVR tick timer question.

### ISSUE THREAD

**Issue by martinmarcos** [greiman/FreeRTOS-Arduino#7]
Thanks @greiman for this Arduino port of FreeRTOS, its great! I've been using it for some simple applications and mostly following the examples.

Now I got to do some applications where tasks have to wait for long periods of time and it got me wondering how long can the vTaskDelay and vTaskDelayUntil functions wait for. I am not really familiarized with the avr architecture (I've worked mostly with arm cortex-m) but I took a look at the port.c to see what timer you were using and it seems like you are using timer0, correct?

``` c
#if 1 // WHG
/*-----------------------------------------------------------*/
/*
 * Setup timer 0 compare match A to generate a tick interrupt.
 */
static void prvSetupTimerInterrupt( void )
{
  OCR0A = 1;
  TIMSK0  |= (1 << OCIE0A);
}
#if configUSE_PREEMPTION == 1
```
Not sure what the ISR configuration is in this case. The comment indicates that it interrupts due to a comparator match A, but I don't understand the configuration.

I also saw that there is a hard-coded conditional preprocessor directive that excludes timer1 configuration functions with a "WHG" comment. 
``` c
#else  // WHG
/*
 * Setup timer 1 compare match A to generate a tick interrupt.
 */
static void prvSetupTimerInterrupt( void )
{
uint32_t ulCompareMatch;
uint8_t ucHighByte, ucLowByte;
...
```

What does WHG stand for?
It would be awesome to get some insight!
Thanks again.
Martin.

**Comment by greiman** [comment]
The maximum delay depends on the configuration parameter configUSE_16_BIT_TICKS.  It is set to one in  FreeRTOSConfig.h

Here is the code in portmacro.h that defines the max delay.
```
#if( configUSE_16_BIT_TICKS == 1 )
	typedef uint16_t TickType_t;
	#define portMAX_DELAY ( TickType_t ) 0xffff
#else
	typedef uint32_t TickType_t;
	#define portMAX_DELAY ( TickType_t ) 0xffffffffUL
#endif
```
 I set the tick rate as follows.  For a 16 MHz Arduino this is 976 Hz.

#define configTICK_RATE_HZ			( ( TickType_t ) (F_CPU/16384L))

The 16384 factor is set for timer zero by the Arduino IDE.

For a 16 bit TickType_t the max delay is about 67 = 65535/976 seconds.

If you set configUSE_16_BIT_TICKS  to zero for 32 bits, the time will be about 50 days.

WHG are my initials.  I use it to mark mods.

**Comment by martinmarcos** [comment]
Ok, I think I am going to have to use 32bits for TickType_t because I need delays of several minutes.
Thanks!
Martin.
